#!/usr/bin/perl

use strict;
use ceilingLight;
use pwhd;
use Time::HiRes qw(usleep time);


ceilingLight::init();
pwhd::init();


my $h = 0;


while(1)
{

	pwhd::setAll(255,0,0);
	ceilingLight::setColor(0x0,255,0,0,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
	pwhd::setAll(255,255,0);
	ceilingLight::setColor(0x0,255,255,0,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
	pwhd::setAll(0,255,0);
	ceilingLight::setColor(0x0,0,255,0,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
	pwhd::setAll(0,255,255);
	ceilingLight::setColor(0x0,0,255,255,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
	pwhd::setAll(0,0,255);
	ceilingLight::setColor(0x0,0,0,255,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
	pwhd::setAll(255,0,255);
	ceilingLight::setColor(0x0,255,0,255,0);
	usleep(14400);
	pwhd::setAll(0,0,0);
	ceilingLight::setColor(0x0,0,0,0,0);
	usleep(40000);
#	warn (1 / (time-$start) );
}
warn ceilingLight::read();

