#!/usr/bin/perl

use strict;
use ceilingLight;
use pwhd;
use Time::HiRes qw(usleep time);


pwhd::init();
ceilingLight::init();
	ceilingLight::setColor(0,0,0,0,255);


my $h = 0;


while(1)
{
	my $start = time;
	$h+=1.12;
	

	$h = 0 if $h >= 360;

#	warn $h;

	(my $r2,my $g2,my $b2) = ceilingLight::hsv2rgb($h,1,1);
	
	my $r1 = int($r2*155);
	my $g1 = int($g2*155);
	my $b1 = int($b2*155);

	my $sum = $r1+$g1+$b1;

	my $div = $sum / 255;


#	$r1 /= $div;
#	$g1 /= $div;
#	$b1 /= $div;

	warn $r1;

	pwhd::setAll($r1,$g1,$b1);
#	ceilingLight::readline();	

	usleep(4000);
	warn (1 / (time-$start) );
}
warn ceilingLight::read();

