#!/usr/bin/perl

use strict;
use ceilingLight;
use Time::HiRes qw(usleep time);


ceilingLight::init();


my $h = 0;


while(1)
{
	my $start = time;
	$h+=3.12;
	

	$h = 0 if $h >= 360;

#	warn $h;

	(my $r2,my $g2,my $b2) = ceilingLight::hsv2rgb($h,1,1);
	
	my $r1 = int($r2*155);
	my $g1 = int($g2*155);
	my $b1 = int($b2*155);

	my $sum = $r1+$g1+$b1;

	my $div = $sum / 255;


#	$r1 /= $div;
#	$g1 /= $div;
#	$b1 /= $div;

	warn $r1;

	ceilingLight::setColor(1,$r1,$g1,$b1,0);
	ceilingLight::setColor(2,$r1,$g1,$b1,0);
	ceilingLight::setColor(3,$r1,$g1,$b1,0);
	ceilingLight::setColor(4,$r1,$g1,$b1,0);
	ceilingLight::setColor(5,$r1,$g1,$b1,255);
#	ceilingLight::readline();	

	usleep(40000);
#	warn (1 / (time-$start) );
}
warn ceilingLight::read();

