#!/usr/bin/perl

use strict;
use ceilingLight;
use Time::HiRes qw(usleep time);


ceilingLight::init();


my $h = 0;


while(1)
{

	for(1..100)
	{
		ceilingLight::setColor(0x0,255,0,0,0);
		usleep(8000);
		ceilingLight::setColor(0x0,0,0,255,0);
		usleep(8000);
	}
	for(1..100)
	{
		ceilingLight::setColor(0x0,255,0,0,0);
		usleep(8000);
		ceilingLight::setColor(0x0,0,0,255,0);
		usleep(8000);
	}
	for(1..100)
	{
		ceilingLight::setColor(0x0,255,255,0,0);
		usleep(8000);
		ceilingLight::setColor(0x0,0,0,255,0);
		usleep(8000);
	}
	for(1..100)
	{
		ceilingLight::setColor(0x0,255,0,0,0);
		usleep(8000);
		ceilingLight::setColor(0x0,0,255,0,0);
		usleep(8000);
		ceilingLight::setColor(0x0,0,0,255,0);
		usleep(8000);
	}
#	warn (1 / (time-$start) );
}
warn ceilingLight::read();

