#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEF4");
$port->databits(8);
$port->baudrate(115200);
$port->parity("none");
$port->stopbits(1);


while(1)
{
	my $return=$port->write(chr(66).chr(00).chr(00).chr(1).chr(0).chr(0));
	usleep(200000);
}
warn $port->read(1);
