#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEF2");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);

while(1)
{
	my $return=$port->write(chr(0x42).chr(00).chr(00).chr(00).chr(255).chr(0));
	usleep(20000);
	my $return=$port->write(chr(0x42).chr(00).chr(00).chr(00).chr(00).chr(0));
	usleep(20000);
	my $return=$port->write(chr(0x42).chr(00).chr(00).chr(00).chr(00).chr(255));
	usleep(20000);
	my $return=$port->write(chr(0x42).chr(00).chr(00).chr(00).chr(00).chr(0));
	usleep(20000);
}
sleep(1);
warn $port->read(1);
