#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DDXM");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);

	warn (chr(0x42).chr(5).chr(5).chr(0).chr(0).chr(255)); 

my $return=$port->write(chr(0x42).chr(0).chr(0).chr(0).chr(0).chr(2));
sleep(1);
warn $port->read(1);
