#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEEZ");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);

my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(255).chr(0));
sleep(1);
warn $port->read(1);
