#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A2002QDi");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);

while(1)
{
	foreach my $nr (90..250)
	{
#		my $nr = 230;
		my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr($nr));
#		usleep(5600);
	}
	foreach my $nr (reverse (90..250))
	{
#		my $nr = 230;
		my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr($nr));

#		usleep(5600);
	}
}
sleep(1);
warn $port->read(1);
